name: r-multiverse-staging

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  r-multiverse-staging:
    uses: r-multiverse/workflows/.github/workflows/check-staging.yaml@main
    secrets: inherit
